# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zoo',
                'doc_host': 'https://deven-gqc.github.io',
                'git_url': 'https://github.com/deven-gqc/zoo',
                'lib_path': 'zoo'},
  'syms': {'zoo.core': {'zoo.core.foo': ('core.html#foo', 'zoo/core.py')}}}
